import Tree from "./Tree";
import { useState } from "react";
// import { generateTree } from "./randomData";
function createData() {
  return [
    { name: "Eve", parent: "", width: 1825, height: 828 },
    { name: "SSSKG", parent: "Eve", width: 2000, height: 828 },
    { name: "JPIKV", parent: "SSSKG", width: 1173, height: 624 },
    { name: "OXWES", parent: "Eve", width: 1537, height: 1039 },
    { name: "XBGRW", parent: "Eve", width: 1356, height: 905 },
    { name: "ROCNT", parent: "SSSKG", width: 425, height: 313 },
    { name: "CKGTQ", parent: "SSSKG", width: 1353, height: 527 },
    { name: "EPOBB", parent: "Eve", width: 367, height: 278 },
    { name: "FJASQ", parent: "SSSKG", width: 524, height: 1991 },
    { name: "EJHZA", parent: "SSSKG", width: 1604, height: 1919 },
    { name: "KOKID", parent: "SSSKG", width: 1697, height: 991 },
    { name: "LAZHN", parent: "XBGRW", width: 397, height: 507 },
    { name: "GLLOP", parent: "Eve", width: 1074, height: 383 },
    { name: "VKTFI", parent: "SSSKG", width: 1866, height: 1662 },
    { name: "HRUUC", parent: "SSSKG", width: 667, height: 371 },
    { name: "PZAOX", parent: "SSSKG", width: 539, height: 1516 },
    { name: "YMERP", parent: "SSSKG", width: 1722, height: 1103 },
    { name: "LXKYT", parent: "Eve", width: 661, height: 1669 },
    { name: "RCAEV", parent: "SSSKG", width: 380, height: 166 },
    { name: "HEQHX", parent: "SSSKG", width: 2058, height: 1986 },
    { name: "WRSKY", parent: "RCAEV", width: 872, height: 1913 },
    { name: "SYDPK", parent: "GLLOP", width: 919, height: 557 },
    { name: "MPMSF", parent: "SSSKG", width: 1064, height: 1770 },
    { name: "SHACS", parent: "RCAEV", width: 1102, height: 1347 },
    { name: "GUVZD", parent: "XBGRW", width: 109, height: 157 },
    { name: "DBSBE", parent: "SSSKG", width: 1370, height: 137 },
    { name: "UDIUF", parent: "SSSKG", width: 845, height: 2076 },
    { name: "KPLLR", parent: "Eve", width: 2031, height: 1810 },
    { name: "AWOJU", parent: "SSSKG", width: 320, height: 1423 },
    { name: "CJPXH", parent: "GLLOP", width: 353, height: 1301 },
    { name: "SGFJP", parent: "SSSKG", width: 800, height: 848 },
    { name: "WBMKE", parent: "SSSKG", width: 1093, height: 1533 },
    { name: "YZGLV", parent: "XBGRW", width: 1413, height: 1546 },
    { name: "BJQDS", parent: "Eve", width: 804, height: 469 },
    { name: "CUZKS", parent: "SSSKG", width: 1768, height: 1794 },
    { name: "SHJQT", parent: "XBGRW", width: 1948, height: 1439 },
    { name: "YBCIU", parent: "XBGRW", width: 1142, height: 1916 },
    { name: "EWPWM", parent: "Eve", width: 855, height: 413 },
    { name: "IBYZJ", parent: "SSSKG", width: 676, height: 1360 },
    { name: "MFBDP", parent: "SSSKG", width: 520, height: 1832 },
    { name: "TCWPW", parent: "SSSKG", width: 990, height: 1650 },
    { name: "YXSXG", parent: "SSSKG", width: 557, height: 2062 },
    { name: "DGNFU", parent: "SSSKG", width: 902, height: 398 },
    { name: "UYSUO", parent: "SSSKG", width: 412, height: 423 },
    { name: "KMMMS", parent: "Eve", width: 288, height: 1342 },
    { name: "CECRR", parent: "SSSKG", width: 1672, height: 1150 },
    { name: "SGPBZ", parent: "Eve", width: 1162, height: 1296 },
    { name: "MBQJY", parent: "SSSKG", width: 1305, height: 489 },
  ];
}

export default function App() {
  // const data = createData();
  const data = [
    {
      name: "Eve",
      parent: "",
      width: 1396,
      height: 364,
    },
    {
      name: "HFIAG",
      parent: "Eve",
      width: 1702,
      height: 1807,
    },
    {
      name: "IRGAF",
      parent: "Eve",
      width: 255,
      height: 797,
    },
    {
      name: "LPLUY",
      parent: "HFIAG",
      width: 1883,
      height: 1375,
    },
    {
      name: "GNYWP",
      parent: "Eve",
      width: 1895,
      height: 885,
    },
    {
      name: "WRBTN",
      parent: "Eve",
      width: 1747,
      height: 1666,
    },
    {
      name: "XYFCN",
      parent: "WRBTN",
      width: 1418,
      height: 764,
    },
    {
      name: "WZAME",
      parent: "HFIAG",
      width: 1594,
      height: 1329,
    },
    {
      name: "DUAJK",
      parent: "GNYWP",
      width: 524,
      height: 128,
    },
    {
      name: "JCEFJ",
      parent: "GNYWP",
      width: 498,
      height: 797,
    },
    {
      name: "WZYXD",
      parent: "Eve",
      width: 1758,
      height: 1231,
    },
    {
      name: "IPJOB",
      parent: "Eve",
      width: 418,
      height: 1647,
    },
    {
      name: "MFBTB",
      parent: "GNYWP",
      width: 1592,
      height: 1576,
    },
    {
      name: "BPCRI",
      parent: "Eve",
      width: 1742,
      height: 262,
    },
    {
      name: "GLMCR",
      parent: "Eve",
      width: 1288,
      height: 1919,
    },
    {
      name: "FLLQP",
      parent: "Eve",
      width: 2097,
      height: 2004,
    },
    {
      name: "BUZGQ",
      parent: "Eve",
      width: 1634,
      height: 1263,
    },
    {
      name: "AXBVK",
      parent: "Eve",
      width: 1752,
      height: 295,
    },
    {
      name: "BOMJT",
      parent: "FLLQP",
      width: 792,
      height: 1190,
    },
    {
      name: "YMNAP",
      parent: "GNYWP",
      width: 305,
      height: 914,
    },
    {
      name: "DEXKV",
      parent: "GNYWP",
      width: 400,
      height: 834,
    },
    {
      name: "EGNPX",
      parent: "Eve",
      width: 419,
      height: 486,
    },
    {
      name: "TWJCW",
      parent: "Eve",
      width: 1684,
      height: 1402,
    },
    {
      name: "TDVKF",
      parent: "Eve",
      width: 1957,
      height: 679,
    },
    {
      name: "VSQDB",
      parent: "GNYWP",
      width: 1342,
      height: 1255,
    },
    {
      name: "OHNHZ",
      parent: "GNYWP",
      width: 1519,
      height: 1524,
    },
    {
      name: "GIKQE",
      parent: "Eve",
      width: 1330,
      height: 1649,
    },
    {
      name: "SSPHK",
      parent: "GNYWP",
      width: 1661,
      height: 2077,
    },
    {
      name: "FKMRM",
      parent: "GNYWP",
      width: 1242,
      height: 191,
    },
    {
      name: "XAWXG",
      parent: "GNYWP",
      width: 1977,
      height: 2070,
    },
    {
      name: "AJHLO",
      parent: "Eve",
      width: 1860,
      height: 1868,
    },
    {
      name: "YYURL",
      parent: "GNYWP",
      width: 1765,
      height: 1506,
    },
    {
      name: "DALAK",
      parent: "GNYWP",
      width: 576,
      height: 1494,
    },
    {
      name: "NHDTG",
      parent: "WRBTN",
      width: 935,
      height: 952,
    },
    {
      name: "VNQUH",
      parent: "GNYWP",
      width: 1899,
      height: 391,
    },
    {
      name: "DZEIG",
      parent: "Eve",
      width: 928,
      height: 956,
    },
    {
      name: "XTENN",
      parent: "GNYWP",
      width: 1370,
      height: 2078,
    },
    {
      name: "CTVEX",
      parent: "GNYWP",
      width: 164,
      height: 370,
    },
    {
      name: "PAPOJ",
      parent: "Eve",
      width: 286,
      height: 400,
    },
    {
      name: "BSHKR",
      parent: "Eve",
      width: 1290,
      height: 1009,
    },
    {
      name: "DJWQU",
      parent: "GNYWP",
      width: 313,
      height: 1443,
    },
    {
      name: "SCWMH",
      parent: "Eve",
      width: 1643,
      height: 260,
    },
    {
      name: "ZMBFF",
      parent: "GNYWP",
      width: 512,
      height: 455,
    },
    {
      name: "RCYHQ",
      parent: "Eve",
      width: 160,
      height: 229,
    },
    {
      name: "JDCVH",
      parent: "GNYWP",
      width: 1291,
      height: 663,
    },
    {
      name: "UXAJC",
      parent: "GNYWP",
      width: 2026,
      height: 410,
    },
    {
      name: "AHAGI",
      parent: "Eve",
      width: 1149,
      height: 466,
    },
    {
      name: "HGDAU",
      parent: "GNYWP",
      width: 784,
      height: 768,
    },
    {
      name: "RTQFM",
      parent: "Eve",
      width: 245,
      height: 1575,
    },
    {
      name: "TBKUA",
      parent: "GNYWP",
      width: 1582,
      height: 938,
    },
    {
      name: "AGVQE",
      parent: "Eve",
      width: 1430,
      height: 623,
    },
    {
      name: "ZGIDW",
      parent: "Eve",
      width: 1815,
      height: 1944,
    },
    {
      name: "YYXLE",
      parent: "Eve",
      width: 503,
      height: 1526,
    },
    {
      name: "ANQKT",
      parent: "GNYWP",
      width: 656,
      height: 1405,
    },
    {
      name: "NAUOX",
      parent: "Eve",
      width: 964,
      height: 1845,
    },
    {
      name: "WZRGO",
      parent: "Eve",
      width: 1417,
      height: 838,
    },
    {
      name: "BEMRR",
      parent: "Eve",
      width: 1257,
      height: 860,
    },
    {
      name: "PAWIG",
      parent: "FLLQP",
      width: 1581,
      height: 1590,
    },
    {
      name: "BVAPY",
      parent: "WRBTN",
      width: 1470,
      height: 1220,
    },
    {
      name: "OPSDT",
      parent: "Eve",
      width: 1705,
      height: 1991,
    },
    {
      name: "NBVVJ",
      parent: "Eve",
      width: 1755,
      height: 1852,
    },
    {
      name: "DEXIW",
      parent: "GNYWP",
      width: 821,
      height: 487,
    },
    {
      name: "YCOJI",
      parent: "GNYWP",
      width: 1747,
      height: 1650,
    },
    {
      name: "WYTWS",
      parent: "GNYWP",
      width: 1532,
      height: 1904,
    },
    {
      name: "VKJLX",
      parent: "Eve",
      width: 1186,
      height: 856,
    },
    {
      name: "LCCPG",
      parent: "Eve",
      width: 1203,
      height: 371,
    },
    {
      name: "ZVLFN",
      parent: "Eve",
      width: 747,
      height: 1187,
    },
    {
      name: "BDOMW",
      parent: "Eve",
      width: 1448,
      height: 1662,
    },
    {
      name: "VKYLX",
      parent: "Eve",
      width: 677,
      height: 795,
    },
    {
      name: "GNQNB",
      parent: "GNYWP",
      width: 966,
      height: 1926,
    },
    {
      name: "GEJRM",
      parent: "Eve",
      width: 1126,
      height: 1213,
    },
    {
      name: "GLSLR",
      parent: "GNYWP",
      width: 526,
      height: 123,
    },
    {
      name: "JDIYF",
      parent: "Eve",
      width: 274,
      height: 1057,
    },
    {
      name: "KKGQI",
      parent: "Eve",
      width: 495,
      height: 176,
    },
    {
      name: "CKCGD",
      parent: "Eve",
      width: 344,
      height: 773,
    },
    {
      name: "TSYZD",
      parent: "Eve",
      width: 904,
      height: 255,
    },
    {
      name: "TURAX",
      parent: "Eve",
      width: 548,
      height: 629,
    },
    {
      name: "KTBYH",
      parent: "Eve",
      width: 154,
      height: 1132,
    },
    {
      name: "FCFLW",
      parent: "Eve",
      width: 873,
      height: 1463,
    },
    {
      name: "RZVJQ",
      parent: "Eve",
      width: 710,
      height: 1951,
    },
    {
      name: "TUOCC",
      parent: "Eve",
      width: 1675,
      height: 1838,
    },
    {
      name: "POOUA",
      parent: "Eve",
      width: 1745,
      height: 777,
    },
    {
      name: "QOAZF",
      parent: "Eve",
      width: 1390,
      height: 481,
    },
    {
      name: "MCVDU",
      parent: "Eve",
      width: 981,
      height: 1097,
    },
    {
      name: "NOQNR",
      parent: "GNYWP",
      width: 1769,
      height: 2076,
    },
    {
      name: "TLWEV",
      parent: "WRBTN",
      width: 945,
      height: 1434,
    },
    {
      name: "JHJNW",
      parent: "Eve",
      width: 348,
      height: 847,
    },
    {
      name: "LPTZJ",
      parent: "GNYWP",
      width: 664,
      height: 719,
    },
    {
      name: "PBJIH",
      parent: "Eve",
      width: 1774,
      height: 1502,
    },
    {
      name: "QNWCG",
      parent: "Eve",
      width: 1788,
      height: 1174,
    },
    {
      name: "UBJIS",
      parent: "GNYWP",
      width: 1340,
      height: 1390,
    },
    {
      name: "LWFJW",
      parent: "GNYWP",
      width: 1227,
      height: 536,
    },
    {
      name: "ISCQB",
      parent: "GNYWP",
      width: 1676,
      height: 1995,
    },
    {
      name: "EGCCF",
      parent: "GNYWP",
      width: 1646,
      height: 536,
    },
    {
      name: "BUOOI",
      parent: "Eve",
      width: 766,
      height: 495,
    },
    {
      name: "CBZDD",
      parent: "Eve",
      width: 1616,
      height: 633,
    },
    {
      name: "WRSUA",
      parent: "GNYWP",
      width: 1015,
      height: 1972,
    },
    {
      name: "SYJML",
      parent: "Eve",
      width: 1651,
      height: 297,
    },
    {
      name: "ERSRM",
      parent: "GNYWP",
      width: 943,
      height: 1597,
    },
    {
      name: "PNUBL",
      parent: "GNYWP",
      width: 1656,
      height: 534,
    },
    {
      name: "EABCF",
      parent: "GNYWP",
      width: 602,
      height: 1667,
    },
    {
      name: "MHGMT",
      parent: "Eve",
      width: 1160,
      height: 1230,
    },
    {
      name: "HWWLR",
      parent: "FLLQP",
      width: 740,
      height: 683,
    },
    {
      name: "CTSVV",
      parent: "GNYWP",
      width: 103,
      height: 1697,
    },
    {
      name: "PURPO",
      parent: "Eve",
      width: 1617,
      height: 1876,
    },
    {
      name: "QOUVM",
      parent: "Eve",
      width: 1903,
      height: 257,
    },
    {
      name: "QOOEQ",
      parent: "Eve",
      width: 1010,
      height: 711,
    },
    {
      name: "OJPWU",
      parent: "Eve",
      width: 444,
      height: 1035,
    },
    {
      name: "IVYFZ",
      parent: "Eve",
      width: 191,
      height: 1026,
    },
    {
      name: "QTRRU",
      parent: "GNYWP",
      width: 1987,
      height: 782,
    },
    {
      name: "YZDAK",
      parent: "GNYWP",
      width: 1274,
      height: 781,
    },
    {
      name: "BQKWM",
      parent: "Eve",
      width: 583,
      height: 1563,
    },
    {
      name: "EFWRV",
      parent: "Eve",
      width: 340,
      height: 233,
    },
    {
      name: "YXYMS",
      parent: "Eve",
      width: 1850,
      height: 368,
    },
    {
      name: "PMIWW",
      parent: "GNYWP",
      width: 798,
      height: 700,
    },
    {
      name: "WVXEL",
      parent: "FLLQP",
      width: 814,
      height: 697,
    },
    {
      name: "FAGWQ",
      parent: "Eve",
      width: 1335,
      height: 1307,
    },
    {
      name: "KLEBF",
      parent: "GNYWP",
      width: 626,
      height: 1609,
    },
    {
      name: "ADKOL",
      parent: "GNYWP",
      width: 167,
      height: 1459,
    },
    {
      name: "OMAWQ",
      parent: "Eve",
      width: 1312,
      height: 616,
    },
    {
      name: "BMGAE",
      parent: "Eve",
      width: 642,
      height: 1039,
    },
    {
      name: "CSLXL",
      parent: "GNYWP",
      width: 1784,
      height: 760,
    },
    {
      name: "RCJGV",
      parent: "Eve",
      width: 1673,
      height: 1807,
    },
    {
      name: "GHRPO",
      parent: "Eve",
      width: 1194,
      height: 1743,
    },
    {
      name: "TGKGD",
      parent: "Eve",
      width: 2081,
      height: 426,
    },
    {
      name: "QFXNG",
      parent: "GNYWP",
      width: 510,
      height: 1103,
    },
    {
      name: "TYORR",
      parent: "Eve",
      width: 368,
      height: 1660,
    },
    {
      name: "DCVRE",
      parent: "GNYWP",
      width: 1398,
      height: 806,
    },
    {
      name: "JTRUZ",
      parent: "GNYWP",
      width: 1712,
      height: 605,
    },
    {
      name: "XETDJ",
      parent: "GNYWP",
      width: 128,
      height: 878,
    },
    {
      name: "SJSRF",
      parent: "WRBTN",
      width: 2014,
      height: 1562,
    },
    {
      name: "PBKPB",
      parent: "GNYWP",
      width: 1369,
      height: 925,
    },
    {
      name: "OGYSC",
      parent: "Eve",
      width: 343,
      height: 214,
    },
    {
      name: "FOJBK",
      parent: "Eve",
      width: 1320,
      height: 376,
    },
    {
      name: "BZCBJ",
      parent: "Eve",
      width: 2058,
      height: 1000,
    },
    {
      name: "VZBFL",
      parent: "GNYWP",
      width: 905,
      height: 1629,
    },
    {
      name: "JQKFA",
      parent: "Eve",
      width: 1530,
      height: 246,
    },
    {
      name: "NSJNV",
      parent: "Eve",
      width: 577,
      height: 443,
    },
    {
      name: "NITQJ",
      parent: "GNYWP",
      width: 1164,
      height: 540,
    },
    {
      name: "FENCQ",
      parent: "Eve",
      width: 2070,
      height: 2054,
    },
    {
      name: "WAMBD",
      parent: "Eve",
      width: 1352,
      height: 1228,
    },
    {
      name: "PPITO",
      parent: "Eve",
      width: 417,
      height: 936,
    },
    {
      name: "QCIWQ",
      parent: "Eve",
      width: 1739,
      height: 970,
    },
    {
      name: "FLIZO",
      parent: "GNYWP",
      width: 948,
      height: 356,
    },
    {
      name: "AUBLV",
      parent: "Eve",
      width: 1892,
      height: 468,
    },
    {
      name: "BLJYG",
      parent: "Eve",
      width: 326,
      height: 2065,
    },
    {
      name: "IWVRG",
      parent: "Eve",
      width: 617,
      height: 1978,
    },
    {
      name: "MXFAT",
      parent: "Eve",
      width: 1421,
      height: 1331,
    },
    {
      name: "KGSNG",
      parent: "Eve",
      width: 139,
      height: 458,
    },
    {
      name: "DZGKO",
      parent: "GNYWP",
      width: 1873,
      height: 285,
    },
    {
      name: "AISQK",
      parent: "Eve",
      width: 287,
      height: 2073,
    },
    {
      name: "DRGUW",
      parent: "Eve",
      width: 940,
      height: 1581,
    },
    {
      name: "CGZHR",
      parent: "Eve",
      width: 1894,
      height: 595,
    },
    {
      name: "ODBUI",
      parent: "Eve",
      width: 1147,
      height: 949,
    },
    {
      name: "ZPVZB",
      parent: "Eve",
      width: 794,
      height: 2060,
    },
    {
      name: "WICML",
      parent: "Eve",
      width: 2067,
      height: 676,
    },
    {
      name: "KWYYD",
      parent: "GNYWP",
      width: 1755,
      height: 2012,
    },
    {
      name: "XZKIU",
      parent: "GNYWP",
      width: 1169,
      height: 1951,
    },
    {
      name: "JLDQM",
      parent: "Eve",
      width: 1736,
      height: 399,
    },
    {
      name: "ADVQC",
      parent: "GNYWP",
      width: 1602,
      height: 1063,
    },
    {
      name: "XPHOX",
      parent: "FLLQP",
      width: 673,
      height: 533,
    },
    {
      name: "FSDVB",
      parent: "Eve",
      width: 681,
      height: 1629,
    },
    {
      name: "RJDGM",
      parent: "Eve",
      width: 400,
      height: 1049,
    },
    {
      name: "FJGRG",
      parent: "GNYWP",
      width: 1033,
      height: 441,
    },
    {
      name: "PSTLT",
      parent: "Eve",
      width: 1933,
      height: 1265,
    },
    {
      name: "UTSRX",
      parent: "Eve",
      width: 677,
      height: 2033,
    },
    {
      name: "PFNBD",
      parent: "Eve",
      width: 1163,
      height: 1044,
    },
    {
      name: "JZEIQ",
      parent: "Eve",
      width: 1664,
      height: 319,
    },
    {
      name: "WETWX",
      parent: "Eve",
      width: 1950,
      height: 882,
    },
    {
      name: "OABVJ",
      parent: "Eve",
      width: 219,
      height: 1797,
    },
    {
      name: "YMJYW",
      parent: "Eve",
      width: 1423,
      height: 801,
    },
    {
      name: "JDTRJ",
      parent: "GNYWP",
      width: 1926,
      height: 812,
    },
    {
      name: "LTZKE",
      parent: "GNYWP",
      width: 613,
      height: 1589,
    },
    {
      name: "YZPBC",
      parent: "Eve",
      width: 1885,
      height: 1781,
    },
    {
      name: "MTYDT",
      parent: "Eve",
      width: 1450,
      height: 272,
    },
    {
      name: "YCKAJ",
      parent: "Eve",
      width: 1203,
      height: 1904,
    },
    {
      name: "ZHRYP",
      parent: "Eve",
      width: 1628,
      height: 2080,
    },
    {
      name: "ZHVHW",
      parent: "GNYWP",
      width: 1413,
      height: 263,
    },
    {
      name: "JYCIL",
      parent: "Eve",
      width: 1992,
      height: 1972,
    },
    {
      name: "UMIER",
      parent: "GNYWP",
      width: 2072,
      height: 2039,
    },
    {
      name: "IHONL",
      parent: "Eve",
      width: 1413,
      height: 675,
    },
    {
      name: "WPUTH",
      parent: "Eve",
      width: 1456,
      height: 729,
    },
    {
      name: "FPCWK",
      parent: "Eve",
      width: 299,
      height: 1094,
    },
    {
      name: "TEORJ",
      parent: "Eve",
      width: 2034,
      height: 1607,
    },
    {
      name: "JLZXG",
      parent: "Eve",
      width: 210,
      height: 1497,
    },
    {
      name: "DKQPM",
      parent: "Eve",
      width: 1039,
      height: 1620,
    },
    {
      name: "NJHBQ",
      parent: "Eve",
      width: 789,
      height: 781,
    },
    {
      name: "AMILC",
      parent: "GNYWP",
      width: 206,
      height: 1704,
    },
    {
      name: "BJFFE",
      parent: "GNYWP",
      width: 991,
      height: 533,
    },
    {
      name: "AEGBI",
      parent: "Eve",
      width: 786,
      height: 1034,
    },
    {
      name: "ZANDY",
      parent: "Eve",
      width: 747,
      height: 330,
    },
    {
      name: "ZEZLY",
      parent: "Eve",
      width: 1498,
      height: 1041,
    },
    {
      name: "MCYGY",
      parent: "Eve",
      width: 829,
      height: 1643,
    },
    {
      name: "MEJEM",
      parent: "Eve",
      width: 1877,
      height: 1447,
    },
    {
      name: "INKQM",
      parent: "Eve",
      width: 1858,
      height: 322,
    },
    {
      name: "EYQBZ",
      parent: "GNYWP",
      width: 932,
      height: 308,
    },
    {
      name: "PPTTZ",
      parent: "Eve",
      width: 2035,
      height: 1141,
    },
    {
      name: "MIWEG",
      parent: "Eve",
      width: 1227,
      height: 1108,
    },
    {
      name: "GKPYL",
      parent: "GNYWP",
      width: 892,
      height: 489,
    },
    {
      name: "JBGAA",
      parent: "GNYWP",
      width: 1213,
      height: 276,
    },
    {
      name: "AEVIH",
      parent: "Eve",
      width: 1275,
      height: 1899,
    },
    {
      name: "KJPMF",
      parent: "GNYWP",
      width: 628,
      height: 1297,
    },
    {
      name: "SGFXB",
      parent: "GNYWP",
      width: 1489,
      height: 1391,
    },
    {
      name: "OPKLL",
      parent: "GNYWP",
      width: 463,
      height: 969,
    },
    {
      name: "QVQCX",
      parent: "GNYWP",
      width: 834,
      height: 923,
    },
    {
      name: "MTWLV",
      parent: "GNYWP",
      width: 1593,
      height: 948,
    },
    {
      name: "AUHQV",
      parent: "GNYWP",
      width: 867,
      height: 1752,
    },
    {
      name: "XLXHG",
      parent: "Eve",
      width: 1299,
      height: 749,
    },
    {
      name: "ULWKT",
      parent: "Eve",
      width: 482,
      height: 396,
    },
    {
      name: "SHESW",
      parent: "Eve",
      width: 690,
      height: 1644,
    },
    {
      name: "SXWEG",
      parent: "GNYWP",
      width: 1806,
      height: 1843,
    },
    {
      name: "OWPWM",
      parent: "GNYWP",
      width: 266,
      height: 1469,
    },
    {
      name: "KGBTL",
      parent: "GNYWP",
      width: 2070,
      height: 1788,
    },
    {
      name: "XYGLD",
      parent: "GNYWP",
      width: 258,
      height: 960,
    },
    {
      name: "TBHXN",
      parent: "Eve",
      width: 158,
      height: 2023,
    },
    {
      name: "CGHUD",
      parent: "GNYWP",
      width: 1070,
      height: 1460,
    },
    {
      name: "PANYB",
      parent: "Eve",
      width: 1280,
      height: 2031,
    },
    {
      name: "ZGMQA",
      parent: "GNYWP",
      width: 1674,
      height: 1630,
    },
    {
      name: "LTCKN",
      parent: "Eve",
      width: 190,
      height: 718,
    },
    {
      name: "YLWGR",
      parent: "Eve",
      width: 784,
      height: 487,
    },
    {
      name: "MWMNT",
      parent: "Eve",
      width: 125,
      height: 1990,
    },
    {
      name: "MDCIP",
      parent: "GNYWP",
      width: 2089,
      height: 1092,
    },
    {
      name: "GYAVN",
      parent: "WRBTN",
      width: 1019,
      height: 381,
    },
    {
      name: "DUBNT",
      parent: "GNYWP",
      width: 348,
      height: 1640,
    },
    {
      name: "IWFTW",
      parent: "Eve",
      width: 310,
      height: 1528,
    },
    {
      name: "DHJKE",
      parent: "Eve",
      width: 508,
      height: 1863,
    },
    {
      name: "BHPLL",
      parent: "Eve",
      width: 1481,
      height: 2016,
    },
    {
      name: "XEDMD",
      parent: "GNYWP",
      width: 1798,
      height: 1513,
    },
    {
      name: "DQIAJ",
      parent: "Eve",
      width: 1279,
      height: 1745,
    },
    {
      name: "IQSBV",
      parent: "Eve",
      width: 2040,
      height: 1693,
    },
    {
      name: "HZIMP",
      parent: "Eve",
      width: 1894,
      height: 491,
    },
    {
      name: "KUYBZ",
      parent: "Eve",
      width: 165,
      height: 1172,
    },
    {
      name: "ADQTA",
      parent: "Eve",
      width: 1682,
      height: 1412,
    },
    {
      name: "RBQLO",
      parent: "GNYWP",
      width: 1486,
      height: 431,
    },
    {
      name: "PLMSF",
      parent: "Eve",
      width: 1399,
      height: 835,
    },
    {
      name: "FRTCG",
      parent: "GNYWP",
      width: 627,
      height: 1897,
    },
    {
      name: "OOHSP",
      parent: "Eve",
      width: 1931,
      height: 1625,
    },
    {
      name: "WZAAS",
      parent: "Eve",
      width: 1076,
      height: 641,
    },
    {
      name: "GLVNL",
      parent: "GNYWP",
      width: 1563,
      height: 443,
    },
    {
      name: "HONXO",
      parent: "Eve",
      width: 1217,
      height: 781,
    },
    {
      name: "NODGH",
      parent: "Eve",
      width: 585,
      height: 1641,
    },
    {
      name: "QKGCT",
      parent: "Eve",
      width: 338,
      height: 643,
    },
    {
      name: "HVVAX",
      parent: "Eve",
      width: 903,
      height: 836,
    },
    {
      name: "SHOBE",
      parent: "Eve",
      width: 117,
      height: 1750,
    },
    {
      name: "ZCEWV",
      parent: "Eve",
      width: 391,
      height: 1471,
    },
    {
      name: "PMXXA",
      parent: "Eve",
      width: 986,
      height: 1152,
    },
    {
      name: "BLRUC",
      parent: "GNYWP",
      width: 1712,
      height: 1531,
    },
    {
      name: "ZQEUW",
      parent: "Eve",
      width: 614,
      height: 1866,
    },
    {
      name: "APJWF",
      parent: "GNYWP",
      width: 1927,
      height: 1679,
    },
    {
      name: "HUQVV",
      parent: "FLLQP",
      width: 1102,
      height: 982,
    },
    {
      name: "WHMBV",
      parent: "Eve",
      width: 890,
      height: 883,
    },
    {
      name: "OVGFR",
      parent: "Eve",
      width: 1042,
      height: 1380,
    },
    {
      name: "FNBBP",
      parent: "GNYWP",
      width: 520,
      height: 348,
    },
    {
      name: "PWYGA",
      parent: "GNYWP",
      width: 1455,
      height: 1012,
    },
    {
      name: "IZADD",
      parent: "Eve",
      width: 844,
      height: 838,
    },
    {
      name: "DVYGY",
      parent: "GNYWP",
      width: 1279,
      height: 302,
    },
    {
      name: "AJWUP",
      parent: "Eve",
      width: 1374,
      height: 1002,
    },
    {
      name: "FGPOB",
      parent: "Eve",
      width: 445,
      height: 1979,
    },
    {
      name: "FTNPN",
      parent: "GNYWP",
      width: 686,
      height: 1071,
    },
    {
      name: "JSQUN",
      parent: "Eve",
      width: 376,
      height: 1543,
    },
    {
      name: "ZUQOO",
      parent: "Eve",
      width: 896,
      height: 1377,
    },
    {
      name: "UFIKT",
      parent: "GNYWP",
      width: 1547,
      height: 435,
    },
    {
      name: "RXAAQ",
      parent: "Eve",
      width: 1998,
      height: 836,
    },
    {
      name: "QKBND",
      parent: "Eve",
      width: 1723,
      height: 2040,
    },
    {
      name: "NHERE",
      parent: "GNYWP",
      width: 477,
      height: 249,
    },
    {
      name: "QFDIB",
      parent: "GNYWP",
      width: 191,
      height: 1678,
    },
    {
      name: "VZLZG",
      parent: "GNYWP",
      width: 1585,
      height: 1926,
    },
    {
      name: "QRGGS",
      parent: "Eve",
      width: 287,
      height: 868,
    },
    {
      name: "ZKDYM",
      parent: "Eve",
      width: 1949,
      height: 1828,
    },
    {
      name: "CAKNW",
      parent: "Eve",
      width: 1969,
      height: 777,
    },
    {
      name: "WZNSD",
      parent: "Eve",
      width: 1906,
      height: 1928,
    },
    {
      name: "ORZDA",
      parent: "Eve",
      width: 1005,
      height: 1775,
    },
    {
      name: "LJJNU",
      parent: "GNYWP",
      width: 1256,
      height: 408,
    },
    {
      name: "JUQGU",
      parent: "Eve",
      width: 1811,
      height: 1787,
    },
    {
      name: "CXVBU",
      parent: "Eve",
      width: 1399,
      height: 119,
    },
    {
      name: "EMAVT",
      parent: "Eve",
      width: 1252,
      height: 1165,
    },
    {
      name: "WHARW",
      parent: "GNYWP",
      width: 829,
      height: 1056,
    },
    {
      name: "TPKGD",
      parent: "GNYWP",
      width: 1715,
      height: 167,
    },
    {
      name: "RFDHF",
      parent: "Eve",
      width: 454,
      height: 1359,
    },
    {
      name: "HCLGZ",
      parent: "Eve",
      width: 1808,
      height: 560,
    },
    {
      name: "EZQOD",
      parent: "Eve",
      width: 681,
      height: 1797,
    },
    {
      name: "LYBQA",
      parent: "GNYWP",
      width: 1239,
      height: 1502,
    },
    {
      name: "AQJXJ",
      parent: "GNYWP",
      width: 1838,
      height: 1816,
    },
    {
      name: "OIQWF",
      parent: "Eve",
      width: 1672,
      height: 2001,
    },
    {
      name: "YEUAK",
      parent: "Eve",
      width: 1125,
      height: 1691,
    },
    {
      name: "TLWZW",
      parent: "Eve",
      width: 1080,
      height: 1787,
    },
    {
      name: "XLLKT",
      parent: "Eve",
      width: 688,
      height: 774,
    },
    {
      name: "ZNASJ",
      parent: "GNYWP",
      width: 1826,
      height: 1623,
    },
    {
      name: "JQWRS",
      parent: "Eve",
      width: 1559,
      height: 460,
    },
    {
      name: "WMCUM",
      parent: "FLLQP",
      width: 1234,
      height: 413,
    },
    {
      name: "PDFNO",
      parent: "GNYWP",
      width: 564,
      height: 1871,
    },
    {
      name: "PRANY",
      parent: "Eve",
      width: 279,
      height: 2020,
    },
    {
      name: "FHRGJ",
      parent: "Eve",
      width: 1888,
      height: 291,
    },
    {
      name: "VCIFP",
      parent: "GNYWP",
      width: 1252,
      height: 202,
    },
    {
      name: "QRDKS",
      parent: "GNYWP",
      width: 1069,
      height: 1018,
    },
    {
      name: "EUSXU",
      parent: "Eve",
      width: 546,
      height: 975,
    },
    {
      name: "WKARX",
      parent: "GNYWP",
      width: 1962,
      height: 2096,
    },
    {
      name: "PKMWH",
      parent: "GNYWP",
      width: 445,
      height: 411,
    },
    {
      name: "TWFBZ",
      parent: "Eve",
      width: 1222,
      height: 1445,
    },
    {
      name: "BOMVR",
      parent: "Eve",
      width: 644,
      height: 854,
    },
    {
      name: "GRZWN",
      parent: "Eve",
      width: 247,
      height: 1992,
    },
    {
      name: "YCRLT",
      parent: "Eve",
      width: 364,
      height: 1134,
    },
    {
      name: "BOSEQ",
      parent: "Eve",
      width: 1626,
      height: 1564,
    },
    {
      name: "HDAQN",
      parent: "Eve",
      width: 1091,
      height: 1680,
    },
    {
      name: "XKRJB",
      parent: "GNYWP",
      width: 742,
      height: 651,
    },
    {
      name: "UZSNL",
      parent: "GNYWP",
      width: 1673,
      height: 1518,
    },
    {
      name: "YIDZW",
      parent: "Eve",
      width: 744,
      height: 1310,
    },
    {
      name: "CPCVH",
      parent: "Eve",
      width: 1658,
      height: 1077,
    },
    {
      name: "KFHBE",
      parent: "GNYWP",
      width: 250,
      height: 211,
    },
    {
      name: "OHSAI",
      parent: "GNYWP",
      width: 221,
      height: 1271,
    },
    {
      name: "KBBEM",
      parent: "Eve",
      width: 628,
      height: 621,
    },
    {
      name: "EYDKN",
      parent: "GNYWP",
      width: 1394,
      height: 1128,
    },
    {
      name: "CRITH",
      parent: "GNYWP",
      width: 1149,
      height: 1620,
    },
    {
      name: "WUPJN",
      parent: "Eve",
      width: 130,
      height: 1241,
    },
    {
      name: "DUTKP",
      parent: "GNYWP",
      width: 112,
      height: 890,
    },
    {
      name: "IWKMI",
      parent: "GNYWP",
      width: 1563,
      height: 1400,
    },
    {
      name: "TJXNP",
      parent: "GNYWP",
      width: 231,
      height: 1307,
    },
    {
      name: "QGVBS",
      parent: "GNYWP",
      width: 1513,
      height: 855,
    },
    {
      name: "LFMOZ",
      parent: "Eve",
      width: 582,
      height: 1747,
    },
    {
      name: "XFZAF",
      parent: "Eve",
      width: 1222,
      height: 415,
    },
    {
      name: "HHNRS",
      parent: "WRBTN",
      width: 675,
      height: 650,
    },
    {
      name: "HSZQK",
      parent: "Eve",
      width: 655,
      height: 1915,
    },
    {
      name: "CQUHS",
      parent: "GNYWP",
      width: 1869,
      height: 1546,
    },
    {
      name: "JWCFC",
      parent: "Eve",
      width: 776,
      height: 1434,
    },
    {
      name: "RGNCE",
      parent: "Eve",
      width: 1999,
      height: 489,
    },
    {
      name: "EEUFX",
      parent: "Eve",
      width: 1347,
      height: 785,
    },
    {
      name: "KGNWI",
      parent: "GNYWP",
      width: 611,
      height: 193,
    },
    {
      name: "GCOHQ",
      parent: "Eve",
      width: 2027,
      height: 1318,
    },
    {
      name: "MBEGF",
      parent: "GNYWP",
      width: 988,
      height: 1352,
    },
    {
      name: "NWJNG",
      parent: "Eve",
      width: 1470,
      height: 664,
    },
    {
      name: "SLGIL",
      parent: "GNYWP",
      width: 1419,
      height: 1942,
    },
    {
      name: "KXCPK",
      parent: "GNYWP",
      width: 1670,
      height: 704,
    },
    {
      name: "YPHEB",
      parent: "GNYWP",
      width: 1202,
      height: 1791,
    },
    {
      name: "GQOLU",
      parent: "Eve",
      width: 392,
      height: 230,
    },
    {
      name: "GZSZF",
      parent: "Eve",
      width: 1642,
      height: 1118,
    },
    {
      name: "OJFMV",
      parent: "GNYWP",
      width: 429,
      height: 1361,
    },
    {
      name: "XKQEX",
      parent: "Eve",
      width: 1251,
      height: 2012,
    },
    {
      name: "AJBPG",
      parent: "Eve",
      width: 1057,
      height: 620,
    },
    {
      name: "LBALY",
      parent: "Eve",
      width: 210,
      height: 1365,
    },
    {
      name: "ZJENG",
      parent: "GNYWP",
      width: 401,
      height: 1059,
    },
    {
      name: "GPTUD",
      parent: "GNYWP",
      width: 297,
      height: 467,
    },
    {
      name: "SHVCB",
      parent: "GNYWP",
      width: 1729,
      height: 1377,
    },
    {
      name: "LDGSY",
      parent: "Eve",
      width: 1298,
      height: 1397,
    },
    {
      name: "KJDKL",
      parent: "Eve",
      width: 1160,
      height: 410,
    },
    {
      name: "DFSSY",
      parent: "GNYWP",
      width: 1996,
      height: 848,
    },
    {
      name: "VQCYA",
      parent: "Eve",
      width: 2099,
      height: 1438,
    },
    {
      name: "JFUVA",
      parent: "Eve",
      width: 757,
      height: 1590,
    },
    {
      name: "YBJLG",
      parent: "GNYWP",
      width: 681,
      height: 1663,
    },
    {
      name: "QMAQX",
      parent: "GNYWP",
      width: 664,
      height: 675,
    },
    {
      name: "MHMPC",
      parent: "Eve",
      width: 146,
      height: 593,
    },
    {
      name: "YLLON",
      parent: "GNYWP",
      width: 373,
      height: 1401,
    },
    {
      name: "BMHZN",
      parent: "GNYWP",
      width: 1369,
      height: 199,
    },
    {
      name: "RRNZE",
      parent: "GNYWP",
      width: 515,
      height: 1987,
    },
    {
      name: "LJNWP",
      parent: "Eve",
      width: 742,
      height: 1282,
    },
    {
      name: "RHPMA",
      parent: "GNYWP",
      width: 1684,
      height: 323,
    },
    {
      name: "NMHSI",
      parent: "GNYWP",
      width: 561,
      height: 458,
    },
    {
      name: "XWCLI",
      parent: "Eve",
      width: 2035,
      height: 636,
    },
    {
      name: "UGQFT",
      parent: "Eve",
      width: 1647,
      height: 1007,
    },
    {
      name: "ZEUAE",
      parent: "Eve",
      width: 928,
      height: 643,
    },
    {
      name: "RACSX",
      parent: "Eve",
      width: 1947,
      height: 581,
    },
    {
      name: "QNOOD",
      parent: "Eve",
      width: 1813,
      height: 1702,
    },
    {
      name: "RKDYD",
      parent: "Eve",
      width: 1582,
      height: 1899,
    },
    {
      name: "QEEXW",
      parent: "Eve",
      width: 255,
      height: 499,
    },
    {
      name: "VOQJC",
      parent: "GNYWP",
      width: 517,
      height: 513,
    },
    {
      name: "BJQPZ",
      parent: "Eve",
      width: 774,
      height: 205,
    },
    {
      name: "ZZTZF",
      parent: "GNYWP",
      width: 1765,
      height: 1906,
    },
    {
      name: "IOTAT",
      parent: "GNYWP",
      width: 1908,
      height: 1335,
    },
    {
      name: "PBWJR",
      parent: "GNYWP",
      width: 1176,
      height: 1414,
    },
    {
      name: "SERLH",
      parent: "Eve",
      width: 175,
      height: 880,
    },
    {
      name: "BZYNU",
      parent: "Eve",
      width: 1555,
      height: 773,
    },
    {
      name: "ACTMA",
      parent: "Eve",
      width: 1597,
      height: 1046,
    },
    {
      name: "HLNXX",
      parent: "Eve",
      width: 459,
      height: 562,
    },
    {
      name: "ADUFV",
      parent: "GNYWP",
      width: 902,
      height: 1334,
    },
    {
      name: "BLDXS",
      parent: "GNYWP",
      width: 1318,
      height: 463,
    },
    {
      name: "KPYXS",
      parent: "GNYWP",
      width: 583,
      height: 1398,
    },
    {
      name: "YIUDW",
      parent: "Eve",
      width: 1694,
      height: 941,
    },
    {
      name: "BSDYT",
      parent: "Eve",
      width: 752,
      height: 989,
    },
    {
      name: "OQEHG",
      parent: "Eve",
      width: 255,
      height: 1815,
    },
    {
      name: "LPZVH",
      parent: "Eve",
      width: 1139,
      height: 1326,
    },
    {
      name: "BDYHE",
      parent: "Eve",
      width: 1182,
      height: 1871,
    },
    {
      name: "MJIFR",
      parent: "GNYWP",
      width: 1093,
      height: 1658,
    },
    {
      name: "UFCMK",
      parent: "Eve",
      width: 379,
      height: 278,
    },
    {
      name: "GFKLV",
      parent: "Eve",
      width: 455,
      height: 689,
    },
    {
      name: "UVLIP",
      parent: "Eve",
      width: 1068,
      height: 410,
    },
    {
      name: "OVPLS",
      parent: "Eve",
      width: 867,
      height: 2028,
    },
    {
      name: "UKNQF",
      parent: "GNYWP",
      width: 747,
      height: 136,
    },
    {
      name: "NORPE",
      parent: "GNYWP",
      width: 1705,
      height: 486,
    },
    {
      name: "YLJDR",
      parent: "GNYWP",
      width: 571,
      height: 914,
    },
    {
      name: "KKPDF",
      parent: "Eve",
      width: 1361,
      height: 1144,
    },
    {
      name: "XEJXK",
      parent: "GNYWP",
      width: 1206,
      height: 960,
    },
    {
      name: "NYKEW",
      parent: "GNYWP",
      width: 1932,
      height: 588,
    },
    {
      name: "SEWBB",
      parent: "GNYWP",
      width: 1893,
      height: 604,
    },
    {
      name: "TYIHQ",
      parent: "GNYWP",
      width: 1953,
      height: 1631,
    },
    {
      name: "HQEJQ",
      parent: "GNYWP",
      width: 1074,
      height: 539,
    },
    {
      name: "RAWLQ",
      parent: "Eve",
      width: 1424,
      height: 1665,
    },
    {
      name: "HVRQF",
      parent: "Eve",
      width: 1030,
      height: 1126,
    },
    {
      name: "DIEIN",
      parent: "GNYWP",
      width: 1930,
      height: 1275,
    },
    {
      name: "RMAND",
      parent: "GNYWP",
      width: 1146,
      height: 1943,
    },
    {
      name: "AWXRI",
      parent: "Eve",
      width: 1623,
      height: 686,
    },
    {
      name: "TNSXF",
      parent: "Eve",
      width: 1828,
      height: 1817,
    },
    {
      name: "FUXKK",
      parent: "Eve",
      width: 154,
      height: 283,
    },
    {
      name: "TCBOM",
      parent: "Eve",
      width: 638,
      height: 568,
    },
    {
      name: "GKGOT",
      parent: "Eve",
      width: 1271,
      height: 2011,
    },
    {
      name: "VTGSV",
      parent: "Eve",
      width: 119,
      height: 2082,
    },
    {
      name: "WAKNB",
      parent: "Eve",
      width: 871,
      height: 272,
    },
    {
      name: "NZEXE",
      parent: "Eve",
      width: 307,
      height: 2017,
    },
    {
      name: "SJBAQ",
      parent: "Eve",
      width: 1093,
      height: 784,
    },
    {
      name: "QYRHU",
      parent: "GNYWP",
      width: 1933,
      height: 811,
    },
    {
      name: "BHXTH",
      parent: "Eve",
      width: 907,
      height: 968,
    },
    {
      name: "VRYNQ",
      parent: "GNYWP",
      width: 1151,
      height: 612,
    },
    {
      name: "QAOWE",
      parent: "Eve",
      width: 870,
      height: 1006,
    },
    {
      name: "ZSLKN",
      parent: "GNYWP",
      width: 230,
      height: 803,
    },
    {
      name: "EWNJT",
      parent: "GNYWP",
      width: 1634,
      height: 936,
    },
    {
      name: "VAXNQ",
      parent: "GNYWP",
      width: 1090,
      height: 924,
    },
    {
      name: "DEKAU",
      parent: "Eve",
      width: 607,
      height: 291,
    },
    {
      name: "PCSUN",
      parent: "Eve",
      width: 866,
      height: 1427,
    },
    {
      name: "QQCUK",
      parent: "Eve",
      width: 1592,
      height: 1586,
    },
    {
      name: "SMMHG",
      parent: "Eve",
      width: 1727,
      height: 1062,
    },
    {
      name: "TZFZW",
      parent: "Eve",
      width: 1398,
      height: 1532,
    },
    {
      name: "IPSHQ",
      parent: "GNYWP",
      width: 1811,
      height: 1970,
    },
    {
      name: "TXSDP",
      parent: "Eve",
      width: 1393,
      height: 594,
    },
    {
      name: "CNJDS",
      parent: "Eve",
      width: 500,
      height: 545,
    },
    {
      name: "TJEPG",
      parent: "Eve",
      width: 411,
      height: 1340,
    },
    {
      name: "MKDLT",
      parent: "GNYWP",
      width: 2026,
      height: 261,
    },
    {
      name: "LNKLB",
      parent: "Eve",
      width: 1711,
      height: 690,
    },
    {
      name: "LDPYA",
      parent: "Eve",
      width: 670,
      height: 568,
    },
    {
      name: "CKSAK",
      parent: "GNYWP",
      width: 545,
      height: 1137,
    },
    {
      name: "RPQCZ",
      parent: "Eve",
      width: 602,
      height: 1574,
    },
    {
      name: "TVRTM",
      parent: "Eve",
      width: 1307,
      height: 1166,
    },
    {
      name: "TWOAQ",
      parent: "GNYWP",
      width: 1847,
      height: 852,
    },
    {
      name: "UFFQI",
      parent: "GNYWP",
      width: 602,
      height: 2086,
    },
    {
      name: "QJXBR",
      parent: "Eve",
      width: 342,
      height: 238,
    },
    {
      name: "DMNLC",
      parent: "Eve",
      width: 617,
      height: 566,
    },
    {
      name: "AOGEY",
      parent: "Eve",
      width: 129,
      height: 412,
    },
    {
      name: "LKLGZ",
      parent: "GNYWP",
      width: 1033,
      height: 1522,
    },
    {
      name: "FQQCW",
      parent: "Eve",
      width: 1488,
      height: 517,
    },
    {
      name: "GXJXH",
      parent: "Eve",
      width: 1621,
      height: 248,
    },
    {
      name: "OWXLV",
      parent: "Eve",
      width: 1794,
      height: 1296,
    },
    {
      name: "RYSFO",
      parent: "Eve",
      width: 1660,
      height: 1046,
    },
    {
      name: "QIIWY",
      parent: "GNYWP",
      width: 839,
      height: 1708,
    },
    {
      name: "PTFQN",
      parent: "GNYWP",
      width: 1838,
      height: 1896,
    },
    {
      name: "WAXNZ",
      parent: "Eve",
      width: 921,
      height: 1943,
    },
    {
      name: "VBWYY",
      parent: "GNYWP",
      width: 421,
      height: 897,
    },
    {
      name: "BLLGF",
      parent: "Eve",
      width: 563,
      height: 443,
    },
    {
      name: "TYLWJ",
      parent: "Eve",
      width: 144,
      height: 1545,
    },
    {
      name: "SULBV",
      parent: "Eve",
      width: 2047,
      height: 479,
    },
    {
      name: "ALXED",
      parent: "Eve",
      width: 1933,
      height: 890,
    },
    {
      name: "XSJEA",
      parent: "Eve",
      width: 439,
      height: 2084,
    },
    {
      name: "OREFG",
      parent: "Eve",
      width: 535,
      height: 783,
    },
    {
      name: "KLQGW",
      parent: "GNYWP",
      width: 540,
      height: 705,
    },
    {
      name: "RCAWJ",
      parent: "Eve",
      width: 2012,
      height: 1693,
    },
    {
      name: "RCKEA",
      parent: "Eve",
      width: 1243,
      height: 344,
    },
    {
      name: "SPMOM",
      parent: "Eve",
      width: 1464,
      height: 1094,
    },
    {
      name: "PVMLP",
      parent: "Eve",
      width: 596,
      height: 1590,
    },
    {
      name: "EINXV",
      parent: "GNYWP",
      width: 1938,
      height: 1783,
    },
    {
      name: "DMXWK",
      parent: "Eve",
      width: 362,
      height: 1022,
    },
    {
      name: "GZNWR",
      parent: "GNYWP",
      width: 1507,
      height: 173,
    },
    {
      name: "KCGQQ",
      parent: "GNYWP",
      width: 1120,
      height: 1655,
    },
    {
      name: "BVKXD",
      parent: "GNYWP",
      width: 1116,
      height: 1991,
    },
    {
      name: "VGYDV",
      parent: "GNYWP",
      width: 795,
      height: 947,
    },
    {
      name: "DDWBU",
      parent: "Eve",
      width: 296,
      height: 1919,
    },
    {
      name: "OIZNV",
      parent: "Eve",
      width: 356,
      height: 239,
    },
    {
      name: "IIWAI",
      parent: "GNYWP",
      width: 2017,
      height: 634,
    },
    {
      name: "WZULA",
      parent: "Eve",
      width: 1852,
      height: 507,
    },
    {
      name: "KDCKG",
      parent: "Eve",
      width: 505,
      height: 395,
    },
    {
      name: "INBWR",
      parent: "Eve",
      width: 1472,
      height: 557,
    },
    {
      name: "DDKYD",
      parent: "Eve",
      width: 1720,
      height: 1599,
    },
    {
      name: "MGAJD",
      parent: "Eve",
      width: 1405,
      height: 1505,
    },
    {
      name: "DBECC",
      parent: "Eve",
      width: 2053,
      height: 1716,
    },
    {
      name: "FIGCI",
      parent: "Eve",
      width: 500,
      height: 729,
    },
    {
      name: "TDBOX",
      parent: "Eve",
      width: 689,
      height: 804,
    },
    {
      name: "JMVGN",
      parent: "Eve",
      width: 1818,
      height: 1905,
    },
    {
      name: "BNUON",
      parent: "Eve",
      width: 280,
      height: 245,
    },
    {
      name: "NNZNJ",
      parent: "GNYWP",
      width: 360,
      height: 1351,
    },
    {
      name: "SVTER",
      parent: "Eve",
      width: 1819,
      height: 207,
    },
    {
      name: "SBJQA",
      parent: "GNYWP",
      width: 1081,
      height: 1464,
    },
    {
      name: "XAQDD",
      parent: "GNYWP",
      width: 1279,
      height: 1587,
    },
    {
      name: "BIWWC",
      parent: "GNYWP",
      width: 237,
      height: 1674,
    },
    {
      name: "HYUIF",
      parent: "Eve",
      width: 210,
      height: 612,
    },
    {
      name: "CYCZB",
      parent: "Eve",
      width: 1773,
      height: 1411,
    },
    {
      name: "ZBXYI",
      parent: "Eve",
      width: 1747,
      height: 872,
    },
    {
      name: "ZUMHA",
      parent: "Eve",
      width: 391,
      height: 340,
    },
    {
      name: "MRDCZ",
      parent: "Eve",
      width: 1978,
      height: 164,
    },
    {
      name: "ROOJY",
      parent: "Eve",
      width: 1439,
      height: 1750,
    },
    {
      name: "JFOWV",
      parent: "GNYWP",
      width: 599,
      height: 1886,
    },
    {
      name: "IYBPW",
      parent: "GNYWP",
      width: 1340,
      height: 574,
    },
    {
      name: "NOQBV",
      parent: "Eve",
      width: 1871,
      height: 1012,
    },
    {
      name: "XPVEQ",
      parent: "GNYWP",
      width: 1544,
      height: 1018,
    },
    {
      name: "TRCQA",
      parent: "GNYWP",
      width: 2001,
      height: 1129,
    },
    {
      name: "FQWFW",
      parent: "GNYWP",
      width: 1964,
      height: 1756,
    },
    {
      name: "PYDLN",
      parent: "GNYWP",
      width: 931,
      height: 185,
    },
    {
      name: "OTACL",
      parent: "Eve",
      width: 525,
      height: 1592,
    },
    {
      name: "CBAFD",
      parent: "Eve",
      width: 2006,
      height: 490,
    },
    {
      name: "QKYVI",
      parent: "Eve",
      width: 135,
      height: 1722,
    },
    {
      name: "TQNLG",
      parent: "GNYWP",
      width: 412,
      height: 1435,
    },
    {
      name: "VLOGG",
      parent: "Eve",
      width: 1007,
      height: 1115,
    },
    {
      name: "IJZBL",
      parent: "GNYWP",
      width: 1492,
      height: 1020,
    },
    {
      name: "XYKCX",
      parent: "Eve",
      width: 2057,
      height: 300,
    },
    {
      name: "UJZLH",
      parent: "Eve",
      width: 424,
      height: 1810,
    },
    {
      name: "LCBRN",
      parent: "GNYWP",
      width: 1381,
      height: 926,
    },
    {
      name: "RKZDI",
      parent: "Eve",
      width: 1009,
      height: 377,
    },
    {
      name: "BLHRB",
      parent: "GNYWP",
      width: 1650,
      height: 1408,
    },
    {
      name: "WETNY",
      parent: "GNYWP",
      width: 1244,
      height: 105,
    },
    {
      name: "EBPYX",
      parent: "Eve",
      width: 621,
      height: 320,
    },
    {
      name: "LZUUB",
      parent: "Eve",
      width: 1602,
      height: 641,
    },
    {
      name: "DPOCD",
      parent: "Eve",
      width: 445,
      height: 359,
    },
    {
      name: "YUDRP",
      parent: "Eve",
      width: 583,
      height: 984,
    },
    {
      name: "CKDPW",
      parent: "Eve",
      width: 1252,
      height: 158,
    },
    {
      name: "FYNDI",
      parent: "Eve",
      width: 717,
      height: 1923,
    },
    {
      name: "PWVVT",
      parent: "Eve",
      width: 1647,
      height: 559,
    },
    {
      name: "FLSMT",
      parent: "GNYWP",
      width: 1545,
      height: 327,
    },
    {
      name: "JENBR",
      parent: "GNYWP",
      width: 907,
      height: 1402,
    },
    {
      name: "ZZHCZ",
      parent: "Eve",
      width: 331,
      height: 435,
    },
    {
      name: "ENAVV",
      parent: "Eve",
      width: 1104,
      height: 1702,
    },
    {
      name: "AGRLO",
      parent: "Eve",
      width: 156,
      height: 1637,
    },
    {
      name: "CDUFS",
      parent: "GNYWP",
      width: 550,
      height: 689,
    },
    {
      name: "LZGOG",
      parent: "Eve",
      width: 934,
      height: 658,
    },
    {
      name: "AMULL",
      parent: "GNYWP",
      width: 1492,
      height: 1246,
    },
    {
      name: "SDAQC",
      parent: "GNYWP",
      width: 2041,
      height: 1491,
    },
    {
      name: "XTONI",
      parent: "Eve",
      width: 712,
      height: 450,
    },
    {
      name: "OEXXY",
      parent: "Eve",
      width: 676,
      height: 1537,
    },
    {
      name: "BMJLM",
      parent: "GNYWP",
      width: 359,
      height: 1262,
    },
    {
      name: "XSWDS",
      parent: "Eve",
      width: 1590,
      height: 403,
    },
    {
      name: "KMIMW",
      parent: "Eve",
      width: 611,
      height: 1571,
    },
    {
      name: "BJPEB",
      parent: "Eve",
      width: 1569,
      height: 1533,
    },
    {
      name: "LVSGM",
      parent: "Eve",
      width: 570,
      height: 1031,
    },
    {
      name: "JKRNF",
      parent: "Eve",
      width: 935,
      height: 259,
    },
    {
      name: "FDIHC",
      parent: "Eve",
      width: 2034,
      height: 1863,
    },
  ];

  const [width, setWidth] = useState(1000);
  const [height, setHeight] = useState(1000);
  return (
    <>
      <section className="section">
        <div className="container">
          <h1 className="title">Rooted Tree Drawing</h1>
          <form
            className="input"
            onSubmit={(e) => {
              e.preventDefault();
              const form = e.currentTarget;
              setWidth(Number(form.width.value));
              setHeight(Number(form.height.value));
            }}
          >
            <label htmlFor="width">width:</label>
            <input
              id="width"
              name="width"
              type="number"
              defaultValue={width}
              style={{ marginRight: "10px" }}
            />
            <label htmlFor="height">height:</label>
            <input
              id="height"
              name="height"
              type="number"
              defaultValue={height}
              style={{ marginRight: "10px" }}
            />
            <button
              type="submit"
              style={{ backgroundColor: "#00bfff", padding: "5px" }}
            >
              set
            </button>
          </form>

          <div
            className="box"
            style={{
              width: `${width}px`,
              height: `${height}px`,
              border: "1px solid #ddd",
              boxSizing: "content-box",
              overflow: "hidden",
            }}
          >
            <figure
              className="figure"
              style={{ margin: 0, width: "100%", height: "100%" }}
            >
              <Tree data={data} width={width} height={height} />
            </figure>
          </div>
        </div>
      </section>
    </>
  );
}
